'use strict';

module.exports = Object.freeze({
  MAX_PLAYERS_PER_ROOM:          8,
  MIN_PLAYERS_TO_START:          2,
  ROOM_CODE_LENGTH:              6,

  STARTING_LIVES:                3,
  MIN_WORD_LENGTH:               3,

  BASE_TURN_DURATION_MS:         15000,
  MIN_TURN_DURATION_MS:          7000,
  TURN_DURATION_DECREMENT_MS:    500,
  TIMER_TICK_INTERVAL_MS:        1000,

  WORD_ACCEPTED_DELAY_MS:        1200,
  BOMB_EXPLODE_DELAY_MS:         2500,

  RECONNECT_GRACE_WINDOW_MS:     30000,
  EMPTY_ROOM_TTL_MS:             120000,

  DIFFICULTY_MEDIUM_THRESHOLD:   6,
  DIFFICULTY_HARD_THRESHOLD:     14,

  COMBO_EASY_MIN_MATCHES:        12,
  COMBO_MEDIUM_MIN_MATCHES:      6,
  COMBO_HARD_MIN_MATCHES:        3,

  REMATCH_TIMEOUT_MS:            90000,
  RECENT_WORDS_FEED_SIZE:        5,
});
