'use strict';

module.exports = Object.freeze({
 MIN_WORD_LENGTH:               3,
 BASE_TURN_DURATION_MS: 15000,
 MIN_TURN_DURATION_MS:  7000,
 TURN_DURATION_DECREMENT_MS: 500,
 TIMER_TICK_INTERVAL_MS: 1000,
 WORD_ACCEPTED_DELAY_MS: 1200,
 BOMB_EXPLODE_DELAY_MS: 2500,
 DIFFICULTY_MEDIUM_THRESHOLD: 6,
 DIFFICULTY_HARD_THRESHOLD: 14,
 COMBO_EASY_MIN_MATCHES: 12,
 COMBO_MEDIUM_MIN_MATCHES: 6,
 COMBO_HARD_MIN_MATCHES: 3,
});